import type { Metadata } from "next";
import { fontSans } from "@/app/fonts";

import { cn } from "@/lib/utils";

// == CSS
import "./globals.css";

export const metadata: Metadata = {
  title: "Social Quee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
